<?php
//Custom Layouts
$layouts = array(
		'header_297' => array(
				'name' => 'Building Our Community',
				'template' => '[vc_row el_class=\"ipad-row\"][vc_column icons_position=\"left\"][vc_empty_space alter_height=\"medium\" hide_on_mobile=\"\"][/vc_column][vc_column width=\"5/12\" icons_position=\"left\"][vc_empty_space alter_height=\"large\" hide_on_mobile=\"\" css=\".vc_custom_1492522936980{margin-bottom: 0.35rem !important;}\"][trx_sc_title title_style=\"default\" title_tag=\"h2\" title=\"Building Our Community\" subtitle=\"A Big Family\" description=\"Building a strong sense of community in Greenville school is both important and doable. Our school uses different Community - Building Approaches, that helps us to be a family.\"][vc_empty_space alter_height=\"small\" hide_on_mobile=\"\" css=\".vc_custom_1492522208545{margin-bottom: -1rem !important;}\"][trx_sc_layouts_iconed_text icon=\"icon-double-right\" text1=\"explore school programms\" link=\"/contacts\"][vc_empty_space height=\"0.5rem\" alter_height=\"none\" hide_on_mobile=\"\"][trx_sc_layouts_iconed_text icon=\"icon-double-right\" text1=\"School Community\" link=\"/contacts\"][vc_empty_space alter_height=\"small\" hide_on_mobile=\"\"][trx_sc_button type=\"default\" icon_position=\"left\" icon_type=\"fontawesome\" link=\"/contacts/\" title=\"Make an Appointment\"][vc_empty_space height=\"0\" alter_height=\"none\" hide_on_mobile=\"\" css=\".vc_custom_1492671465375{margin-bottom: 0px !important;}\"][/vc_column][vc_column width=\"7/12\" icons_position=\"left\"][vc_row_inner][vc_column_inner el_class=\"center\" width=\"7/12\" icons_position=\"left\"][vc_empty_space alter_height=\"large\" hide_on_mobile=\"\" css=\".vc_custom_1492522878933{margin-bottom: -2.7rem !important;}\"][vc_single_image image=\"298\" img_size=\"full\" alignment=\"right\"][vc_empty_space height=\"0\" alter_height=\"none\" hide_on_mobile=\"\" css=\".vc_custom_1492672144983{margin-bottom: 0px !important;}\"][/vc_column_inner][vc_column_inner el_class=\"center\" width=\"5/12\" icons_position=\"left\"][vc_single_image image=\"299\" img_size=\"full\"][vc_empty_space alter_height=\"small\" hide_on_mobile=\"\" css=\".vc_custom_1492522174880{margin-bottom: 0.5rem !important;}\"][vc_single_image image=\"300\" img_size=\"full\"][/vc_column_inner][/vc_row_inner][/vc_column][vc_column icons_position=\"left\"][vc_empty_space alter_height=\"medium\" hide_on_mobile=\"\" css=\".vc_custom_1492522991371{margin-bottom: 5.5rem !important;}\"][/vc_column][/vc_row]',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'header'
								),
						'_wpb_shortcodes_custom_css' => '.vc_custom_1492522936980{margin-bottom: 0.35rem !important;}.vc_custom_1492522208545{margin-bottom: -1rem !important;}.vc_custom_1492671465375{margin-bottom: 0px !important;}.vc_custom_1492522878933{margin-bottom: -2.7rem !important;}.vc_custom_1492672144983{margin-bottom: 0px !important;}.vc_custom_1492522174880{margin-bottom: 0.5rem !important;}.vc_custom_1492522991371{margin-bottom: 5.5rem !important;}'
						)
				),
		'header_687' => array(
				'name' => 'Community Life',
				'template' => '[vc_row el_class=\"ipad-row\"][vc_column icons_position=\"left\"][vc_empty_space alter_height=\"huge\" hide_on_mobile=\"\"][/vc_column][vc_column width=\"5/12\" icons_position=\"left\"][vc_empty_space alter_height=\"large\" hide_on_mobile=\"\" css=\".vc_custom_1492003565608{margin-bottom: 2.7rem !important;}\"][trx_sc_title title_style=\"default\" title_tag=\"h2\" title=\"Community|| Life\" subtitle=\"Campus Activities\" description=\"There is always something happening on and off campus, so keep checking the links below. It will give you a taste of the vibrancy of Greenville life.\"][vc_empty_space alter_height=\"small\" hide_on_mobile=\"\" css=\".vc_custom_1492005653689{margin-bottom: -1rem !important;}\"][trx_sc_layouts_iconed_text icon=\"icon-double-right\" text1=\"COMMUNITY DINNERS\" link=\"/contacts\"][vc_empty_space height=\"0.5rem\" alter_height=\"none\" hide_on_mobile=\"\"][trx_sc_layouts_iconed_text icon=\"icon-double-right\" text1=\"COMMUNITY WEEKENDS\" link=\"/contacts\"][vc_empty_space height=\"0.5rem\" alter_height=\"none\" hide_on_mobile=\"\"][trx_sc_layouts_iconed_text icon=\"icon-double-right\" text1=\"WEEKEND ACTIVITIES\" link=\"/contacts\"][/vc_column][vc_column width=\"7/12\" icons_position=\"left\"][vc_row_inner equal_height=\"yes\" content_placement=\"bottom\"][vc_column_inner el_class=\"center\" width=\"7/12\" icons_position=\"left\"][vc_empty_space alter_height=\"large\" hide_on_mobile=\"\" css=\".vc_custom_1492003467095{margin-bottom: -2.6rem !important;}\"][vc_single_image image=\"205\" img_size=\"full\" alignment=\"right\"][vc_empty_space height=\"0\" alter_height=\"none\" hide_on_mobile=\"\" css=\".vc_custom_1492702830404{margin-bottom: 0px !important;}\"][/vc_column_inner][vc_column_inner el_class=\"center\" width=\"5/12\" icons_position=\"left\"][vc_single_image image=\"203\" img_size=\"full\"][vc_empty_space alter_height=\"small\" hide_on_mobile=\"\" css=\".vc_custom_1492003436758{margin-bottom: 0.5rem !important;}\"][vc_single_image image=\"204\" img_size=\"full\"][/vc_column_inner][/vc_row_inner][/vc_column][vc_column icons_position=\"left\"][vc_empty_space alter_height=\"large\" hide_on_mobile=\"\" css=\".vc_custom_1492005786665{margin-bottom: 3.5rem !important;}\"][/vc_column][/vc_row]',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'header'
								),
						'_wpb_shortcodes_custom_css' => '.vc_custom_1492003565608{margin-bottom: 2.7rem !important;}.vc_custom_1492005653689{margin-bottom: -1rem !important;}.vc_custom_1492003467095{margin-bottom: -2.6rem !important;}.vc_custom_1492702830404{margin-bottom: 0px !important;}.vc_custom_1492003436758{margin-bottom: 0.5rem !important;}.vc_custom_1492005786665{margin-bottom: 3.5rem !important;}'
						)
				),
		'footer_11' => array(
				'name' => 'Footer Standard (*Greenville)',
				'template' => '[vc_row row_type=\"normal\" row_delimiter=\"\" row_fixed=\"\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\"][vc_column icons_position=\"left\"][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\"][vc_empty_space alter_height=\"large\" hide_on_mobile=\"\" css=\".vc_custom_1491902517834{margin-bottom: -0.2rem !important;}\"][vc_row_inner][vc_column_inner width=\"1/3\" icons_position=\"left\"][vc_single_image image=\"664\" img_size=\"199x70\" css=\".vc_custom_1492684194196{padding-top: 0.2rem !important;}\"][vc_empty_space hide_on_mobile=\"\" css=\".vc_custom_1491903699971{margin-bottom: 1rem !important;}\"][vc_column_text css=\".vc_custom_1491903709336{padding-right: 3rem !important;}\"]Lorem ipsum dolor sit amet, et alienum electram consulatu pri, modo dolore albucius ea cum. Malis vocibus inimicus.[/vc_column_text][/vc_column_inner][vc_column_inner width=\"1/3\" icons_position=\"left\"][vc_wp_custommenu title=\"Main Information\" nav_menu=\"30\"][/vc_column_inner][vc_column_inner width=\"1/3\" icons_position=\"left\"][vc_wp_text title=\"Subscription\"][mc4wp_form id=\"431\"][/vc_wp_text][/vc_column_inner][/vc_row_inner][vc_empty_space hide_on_mobile=\"\"][/trx_sc_content][/vc_column][/vc_row][vc_row row_type=\"compact\" row_delimiter=\"\" row_fixed=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\"][vc_column icons_position=\"left\"][trx_sc_content size=\"1_1\" float=\"center\" number_position=\"br\" title_style=\"default\" css=\".vc_custom_1491908904750{border-top-width: 1px !important;padding-top: 5px !important;border-top-color: #404144 !important;border-top-style: solid !important;}\"][vc_wp_text]

<a href=\"https://themeforest.net/user/ancorathemes/portfolio\" target=\"_blank\" rel=\"noopener\">AncoraThemes</a> &copy; 2018. All rights reserved.

[/vc_wp_text][/trx_sc_content][/vc_column][/vc_row]',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'footer'
								),
						'_wpb_shortcodes_custom_css' => '.vc_custom_1491902517834{margin-bottom: -0.2rem !important;}.vc_custom_1492684194196{padding-top: 0.2rem !important;}.vc_custom_1491903699971{margin-bottom: 1rem !important;}.vc_custom_1491903709336{padding-right: 3rem !important;}.vc_custom_1491908904750{border-top-width: 1px !important;padding-top: 5px !important;border-top-color: #404144 !important;border-top-style: solid !important;}'
						)
				),
		'header_19' => array(
				'name' => 'Header Fullwidth',
				'template' => '<p>[vc_row equal_height=\"yes\" content_placement=\"middle\" row_type=\"compact\" row_delimiter=\"\" row_fixed=\"1\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" css=\".vc_custom_1492696271559{padding-right: 2em !important;padding-left: 2em !important;}\" el_class=\"ipad-row\"][vc_column width=\"1/6\" column_align=\"left\" icons_position=\"left\" column_type=\"center\" css=\".vc_custom_1491898597385{padding-left: 2.4rem !important;}\"][trx_sc_layouts_logo][/vc_column][vc_column width=\"2/3\" column_align=\"center\" icons_position=\"left\"][vc_empty_space alter_height=\"small\" hide_on_mobile=\"1\" css=\".vc_custom_1491898481825{margin-bottom: 0.4rem !important;}\"][trx_sc_layouts_menu location=\"none\" menu=\"main-menu\" animation_in=\"fadeInUpSmall\" animation_out=\"fadeOutDownSmall\" mobile_button=\"1\" mobile_menu=\"1\" hide_on_mobile=\"1\" burger=\"\" mobile=\"1\" stretch=\"\" mobile_hide=\"1\"][vc_empty_space alter_height=\"small\" hide_on_mobile=\"1\"][/vc_column][vc_column width=\"1/6\" column_align=\"right\" icons_position=\"left\" css=\".vc_custom_1492696199562{padding-top: 0.3rem !important;}\" offset=\"vc_hidden-md vc_hidden-sm vc_hidden-xs\"][trx_sc_layouts_iconed_text icon=\"icon-phone-1\" hide_on_tablet=\"1\" hide_on_mobile=\"1\" text1=\"0 800 555 22 11\" link=\"tel:08005552211\"][trx_sc_layouts_search style=\"normal\" ajax=\"\" hide_on_tablet=\"1\" hide_on_mobile=\"1\"][/vc_column][/vc_row]</p>
',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'header'
								),
						'_wpb_shortcodes_custom_css' => '.vc_custom_1492696271559{padding-right: 2em !important;padding-left: 2em !important;}.vc_custom_1491898597385{padding-left: 2.4rem !important;}.vc_custom_1492696199562{padding-top: 0.3rem !important;}.vc_custom_1491898481825{margin-bottom: 0.4rem !important;}'
						)
				),
		'header_20' => array(
				'name' => 'Header Fullwidth Simple',
				'template' => '<p>[vc_row equal_height=\"yes\" content_placement=\"middle\" row_type=\"compact\" row_delimiter=\"\" row_fixed=\"1\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\" css=\".vc_custom_1492604627378{padding-right: 2em !important;padding-left: 2em !important;}\" el_class=\"ipad-row\"][vc_column width=\"1/6\" column_align=\"left\" icons_position=\"left\" column_type=\"center\" css=\".vc_custom_1492670893826{padding-left: 2.4rem !important;}\" offset=\"vc_col-xs-12\"][trx_sc_layouts_logo][/vc_column][vc_column width=\"2/3\" column_align=\"center\" icons_position=\"left\" offset=\"vc_col-xs-12\"][vc_empty_space alter_height=\"small\" hide_on_mobile=\"1\" css=\".vc_custom_1491898481825{margin-bottom: 0.4rem !important;}\"][trx_sc_layouts_menu location=\"none\" menu=\"main-menu\" animation_in=\"fadeInUpSmall\" animation_out=\"fadeOutDownSmall\" mobile_button=\"1\" mobile_menu=\"1\" hide_on_mobile=\"1\" burger=\"\" mobile=\"1\" stretch=\"\" mobile_hide=\"1\"][vc_empty_space alter_height=\"small\" hide_on_mobile=\"1\"][/vc_column][vc_column width=\"1/6\" column_align=\"right\" icons_position=\"left\" offset=\"vc_hidden-md vc_hidden-sm vc_hidden-xs\" css=\".vc_custom_1492683960677{padding-top: 0.3rem !important;}\"][trx_sc_layouts_iconed_text icon=\"icon-phone-1\" hide_on_tablet=\"1\" hide_on_mobile=\"1\" text1=\"0 800 555 22 11\" link=\"tel:08005552211\"][trx_sc_layouts_search style=\"normal\" ajax=\"\" hide_on_tablet=\"1\" hide_on_mobile=\"1\"][/vc_column][/vc_row][vc_row scheme=\"dark\" row_type=\"normal\" row_delimiter=\"\" row_fixed=\"\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"1\" css=\".vc_custom_1491916403306{background: #f7f7f7 url(http://greenville.ancorathemes.com/wp-content/uploads/2017/02/photo-1.png?id=436) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}\"][vc_column column_align=\"center\" icons_position=\"left\"][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\" padding=\"none\"][vc_empty_space alter_height=\"medium\" hide_on_mobile=\"\" css=\".vc_custom_1491901258491{margin-bottom: 0.8rem !important;}\"][trx_sc_layouts_title title=\"1\" meta=\"\" breadcrumbs=\"1\" icon_type=\"fontawesome\" icon_fontawesome=\"\"][vc_empty_space alter_height=\"small\" hide_on_mobile=\"\" css=\".vc_custom_1491901342506{margin-bottom: 0.8rem !important;}\"][/trx_sc_content][/vc_column][/vc_row]</p>
',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'header'
								),
						'_wpb_shortcodes_custom_css' => '.vc_custom_1492604627378{padding-right: 2em !important;padding-left: 2em !important;}.vc_custom_1491916403306{background: #f7f7f7 url(http://greenville.ancorathemes.com/wp-content/uploads/2017/02/photo-1.png?id=436) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}.vc_custom_1492670893826{padding-left: 2.4rem !important;}.vc_custom_1492683960677{padding-top: 0.3rem !important;}.vc_custom_1491898481825{margin-bottom: 0.4rem !important;}.vc_custom_1491901258491{margin-bottom: 0.8rem !important;}.vc_custom_1491901342506{margin-bottom: 0.8rem !important;}'
						)
				),
		'header_607' => array(
				'name' => 'Header Simple',
				'template' => '[vc_row row_type=\"narrow\" row_delimiter=\"\" row_fixed=\"1\" hide_on_tablet=\"\" hide_on_mobile=\"\" hide_on_frontpage=\"\"][vc_column icons_position=\"left\"][trx_sc_content size=\"1_1\" number_position=\"br\" title_style=\"default\"][vc_row_inner equal_height=\"yes\" content_placement=\"middle\" el_class=\"ipad-row\"][vc_column_inner icons_position=\"left\"][vc_empty_space hide_on_mobile=\"\" css=\".vc_custom_1492590480139{margin-bottom: -0.2rem !important;}\"][/vc_column_inner][vc_column_inner width=\"1/4\" icons_position=\"left\"][trx_sc_layouts_logo][/vc_column_inner][vc_column_inner width=\"7/12\" column_align=\"right\" icons_position=\"left\" css=\".vc_custom_1492590585921{padding-right: 0px !important;}\"][trx_sc_layouts_menu location=\"none\" menu=\"menu-2\" animation_in=\"fadeInUpSmall\" animation_out=\"fadeOutDownSmall\" mobile_button=\"1\" mobile_menu=\"1\" hide_on_mobile=\"1\" burger=\"\" mobile=\"1\" stretch=\"\" mobile_hide=\"1\"][/vc_column_inner][vc_column_inner width=\"1/6\" icons_position=\"left\" offset=\"vc_hidden-md vc_hidden-sm vc_hidden-xs\"][trx_sc_button type=\"default\" size=\"small\" align=\"right\" icon_position=\"left\" link=\"/contacts\" title=\"contact us\"][/vc_column_inner][vc_column_inner icons_position=\"left\"][vc_empty_space hide_on_mobile=\"\" css=\".vc_custom_1492590507808{margin-bottom: -0.4rem !important;}\"][/vc_column_inner][/vc_row_inner][/trx_sc_content][/vc_column][/vc_row]',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'header'
								),
						'_wpb_shortcodes_custom_css' => '.vc_custom_1492590585921{padding-right: 0px !important;}.vc_custom_1492590480139{margin-bottom: -0.2rem !important;}.vc_custom_1492590507808{margin-bottom: -0.4rem !important;}'
						)
				),
		'header_273' => array(
				'name' => 'Our Video',
				'template' => '[vc_row full_width=\"stretch_row_content_no_spaces\" css=\".vc_custom_1492011771112{background-image: url(http://greenville.ancorathemes.com/wp-content/uploads/2017/03/bg-2.jpg?id=209) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}\"][vc_column icons_position=\"left\"][vc_empty_space alter_height=\"huge\" hide_on_mobile=\"\" css=\".vc_custom_1492011837997{margin-bottom: 1.6rem !important;}\"][trx_sc_title title_style=\"default\" title_tag=\"h2\" title_align=\"center\" title=\"Students Life\" subtitle=\" Our Video\"][vc_empty_space alter_height=\"medium\" hide_on_mobile=\"\" css=\".vc_custom_1492011856573{margin-bottom: 2rem !important;}\"][/vc_column][vc_column icons_position=\"left\" css=\".vc_custom_1492012734776{margin-bottom: -8.3rem !important;}\" el_class=\"overflow\"][rev_slider alias=\"slider-2\"][/vc_column][/vc_row]',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'header'
								),
						'_wpb_shortcodes_custom_css' => '.vc_custom_1492011771112{background-image: url(http://greenville.ancorathemes.com/wp-content/uploads/2017/03/bg-2.jpg?id=209) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}.vc_custom_1492012734776{margin-bottom: -8.3rem !important;}.vc_custom_1492011837997{margin-bottom: 1.6rem !important;}.vc_custom_1492011856573{margin-bottom: 2rem !important;}'
						)
				),
		'header_295' => array(
				'name' => 'Welcome To Greenville',
				'template' => '[vc_row full_width=\"stretch_row\" css=\".vc_custom_1489587950227{background-color: #f2f3f6 !important;}\"][vc_column width=\"1/2\" icons_position=\"left\" offset=\"vc_col-lg-offset-3 vc_col-md-offset-3 vc_col-sm-offset-3 vc_col-xs-12\"][vc_empty_space alter_height=\"huge\" hide_on_mobile=\"\"][trx_sc_title title_style=\"default\" title_tag=\"h2\" title_align=\"center\" title=\"Welcome To Greenville\" subtitle=\"Welcome To Us\" description=\"Our buildings are filled with children and adults who want to come to school every day. They are engaged in activities that light up their brains, sharpen their critical capacities and develop their consciences.\"][vc_empty_space alter_height=\"large\" hide_on_mobile=\"\" css=\".vc_custom_1492509081750{margin-bottom: 1.9rem !important;}\"][/vc_column][/vc_row][vc_row][vc_column icons_position=\"left\"][vc_empty_space height=\"0\" alter_height=\"none\" hide_on_mobile=\"\" css=\".vc_custom_1492685935200{margin-top: -5.3rem !important;}\"][trx_sc_services type=\"list\" featured=\"icon\" featured_position=\"top\" hide_excerpt=\"1\" no_margin=\"\" icons_animation=\"\" cat=\"29\" orderby=\"post_date\" order=\"desc\" slider=\"\" title_style=\"default\" count=\"4\" columns=\"4\"][/vc_column][/vc_row]',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'header'
								),
						'_wpb_shortcodes_custom_css' => '.vc_custom_1489587950227{background-color: #f2f3f6 !important;}.vc_custom_1492509081750{margin-bottom: 1.9rem !important;}.vc_custom_1492685935200{margin-top: -5.3rem !important;}'
						)
				),
		'header_645' => array(
				'name' => 'Welcome To Greenville 2',
				'template' => '[vc_row el_class=\"ipad-row\"][vc_column icons_position=\"left\"][vc_empty_space alter_height=\"large\" hide_on_mobile=\"\" css=\".vc_custom_1492591740958{margin-bottom: 1.9rem !important;}\"][/vc_column][vc_column width=\"5/12\" icons_position=\"left\" offset=\"vc_col-lg-offset-1 vc_col-md-offset-1\"][trx_sc_title title_style=\"default\" title_tag=\"h2\" title=\"Welcome To Greenville\" subtitle=\"A Big Family\" description=\"Building a strong sense of community in Greenville school is both important and doable. Our school uses different Community - Building Approaches, that helps us to be a family.\"][vc_empty_space alter_height=\"small\" hide_on_mobile=\"\" css=\".vc_custom_1492522208545{margin-bottom: -1rem !important;}\"][trx_sc_layouts_iconed_text icon=\"icon-double-right\" text1=\"explore school programms\" link=\"/contacts\"][vc_empty_space height=\"0.5rem\" alter_height=\"none\" hide_on_mobile=\"\"][trx_sc_layouts_iconed_text icon=\"icon-double-right\" text1=\"School Community\" link=\"/contacts\"][vc_empty_space alter_height=\"small\" hide_on_mobile=\"\"][trx_sc_button type=\"default\" icon_position=\"left\" icon_type=\"fontawesome\" link=\"/contacts/\" title=\"Make an Appointment\"][vc_empty_space height=\"0\" alter_height=\"none\" hide_on_mobile=\"\" css=\".vc_custom_1492693996745{margin-bottom: 0px !important;}\"][/vc_column][vc_column width=\"1/2\" icons_position=\"left\"][vc_row_inner][vc_column_inner el_class=\"center\" width=\"2/3\" icons_position=\"left\"][vc_single_image image=\"298\" img_size=\"370x468\"][/vc_column_inner][vc_column_inner el_class=\"grid-style\" width=\"1/2\" icons_position=\"left\"][vc_single_image image=\"300\" img_size=\"195x238\" css=\".vc_custom_1492592967125{border-top-width: 20px !important;border-right-width: 20px !important;border-bottom-width: 20px !important;border-left-width: 20px !important;border-left-color: #ffffff !important;border-left-style: solid !important;border-right-color: #ffffff !important;border-right-style: solid !important;border-top-color: #ffffff !important;border-top-style: solid !important;border-bottom-color: #ffffff !important;border-bottom-style: solid !important;}\"][/vc_column_inner][/vc_row_inner][/vc_column][vc_column icons_position=\"left\"][vc_empty_space alter_height=\"medium\" hide_on_mobile=\"\" css=\".vc_custom_1492593106242{margin-bottom: 0.6rem !important;}\"][/vc_column][/vc_row]',
				'meta' => array(
						'trx_addons_options' => array(
								'layout_type' => 'header'
								),
						'_wpb_shortcodes_custom_css' => '.vc_custom_1492591740958{margin-bottom: 1.9rem !important;}.vc_custom_1492522208545{margin-bottom: -1rem !important;}.vc_custom_1492693996745{margin-bottom: 0px !important;}.vc_custom_1492592967125{border-top-width: 20px !important;border-right-width: 20px !important;border-bottom-width: 20px !important;border-left-width: 20px !important;border-left-color: #ffffff !important;border-left-style: solid !important;border-right-color: #ffffff !important;border-right-style: solid !important;border-top-color: #ffffff !important;border-top-style: solid !important;border-bottom-color: #ffffff !important;border-bottom-style: solid !important;}.vc_custom_1492593106242{margin-bottom: 0.6rem !important;}'
						)
				)
		);
?>